id: P8CF98C65
initial_creation_type: input
source_metadata:
  Title: South Asian classical studies No. 13 (Ṣaḍgatikārikāḥ)
  Editor: Kiyoshi Okano
  Publisher: Kyushu University
  Place of Publication: Fukuoka, Japan
  Year: '2018'
  Ṣaḍgatikārikāḥ:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:21:30.759921'
last_modified_at: '2022-03-08T17:21:30.759929'
